---

# This needs to always run, because it populates `devture_vaultwarden_playbook_uid` and `devture_vaultwarden_playbook_gid`,
# which are required by many other roles.
- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_user.yml"
  tags:
    - always

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags:
    - setup-all
    - install-all
    - setup-vaultwarden
    - install-vaultwarden

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_base_dir.yml"
  tags:
    - setup-all
    - install-all
    - setup-vaultwarden
    - install-vaultwarden
