---

- name: Ensure Vaultwarden paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ devture_vaultwarden_uid }}"
    group: "{{ devture_vaultwarden_gid }}"
  with_items:
    - "{{ devture_vaultwarden_base_path }}"
    - "{{ devture_vaultwarden_data_dir_path }}"
    - "{{ devture_vaultwarden_cache_dir_path }}"
    - "{{ devture_vaultwarden_ephemeral_dir_path }}"

- name: Ensure Vaultwarden support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ devture_vaultwarden_base_path }}/{{ item }}"
    owner: "{{ devture_vaultwarden_uid }}"
    group: "{{ devture_vaultwarden_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure Vaultwarden image is pulled
  community.docker.docker_image:
    name: "{{ devture_vaultwarden_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ devture_vaultwarden_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else devture_vaultwarden_container_image_force_pull }}"

- name: Ensure Vaultwarden container network is created
  community.general.docker_network:
    name: "{{ devture_vaultwarden_container_network }}"
    driver: bridge

- name: Ensure Vaultwarden systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/vaultwarden.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ devture_vaultwarden_identifier }}.service"
    mode: 0640
